// ------------------------------------------------------------------------------
//  <auto-generated>
//      Этот код был создан построителем кодированных тестов ИП.
//      Версия: 16.0.0.0
//
//      Изменения, внесенные в этот файл, могут привести к неправильной работе кода и будут
//      утрачены при повторном формировании кода.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject1
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.31306.167")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1 - Используйте "RecordedMethod1Params" для передачи параметров в этот метод.
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WpfWindow uIWpfWindow = this.UIMainWindowWindow.UIWpfWindow;
            WinTreeItem uIНовыйтомGTreeItem = this.UIОткрытиеWindow.UIДеревоWindow.UIРабочийстолTreeItem.UIЭтоткомпьютерTreeItem.UIНовыйтомGTreeItem;
            WinEdit uIИмяEdit = this.UIОткрытиеWindow.UIItemWindow.UIFtxtListItem.UIИмяEdit;
            WinButton uIОткрытьButton = this.UIОткрытиеWindow.UIОткрытьWindow.UIОткрытьButton;
            WinComboBox uIИмяфайлаComboBox = this.UIСохранениеWindow.UIПанельподробностейPane.UIИмяфайлаComboBox;
            WinButton uIСохранитьButton = this.UIСохранениеWindow.UIСохранитьWindow.UIСохранитьButton;
            WinButton uIДАButton = this.UIСохранениеWindow1.UIДАWindow.UIДАButton;
            #endregion

            // Щелкните "Wpf" окно
            Mouse.Click(uIWpfWindow, new Point(215, 73));

            // Щелкните "Рабочий стол" -> "Этот компьютер" -> "Новый том (G:)" элемент дерева
            Mouse.Click(uIНовыйтомGTreeItem, new Point(59, 14));

            // Щелкните "Имя" надпись
            Mouse.Click(uIИмяEdit, new Point(52, 13));

            // Щелкните "&Открыть" кнопка
            Mouse.Click(uIОткрытьButton, new Point(43, 18));

            // Щелкните "Wpf" окно
            Mouse.Click(uIWpfWindow, new Point(218, 112));

            // Выберите "g" в "Имя файла:" поле со списком
            uIИмяфайлаComboBox.EditableItem = this.RecordedMethod1Params.UIИмяфайлаComboBoxEditableItem;

            // Щелкните "Со&хранить" кнопка
            Mouse.Click(uIСохранитьButton, new Point(54, 15));

            // Щелкните "&Да" кнопка
            Mouse.Click(uIДАButton, new Point(36, 15));

            // Щелкните "Wpf" окно
            Mouse.Click(uIWpfWindow, new Point(68, 142));
        }
        
        /// <summary>
        /// RecordedMethod2 - Используйте "RecordedMethod2Params" для передачи параметров в этот метод.
        /// </summary>
        public void RecordedMethod2()
        {
            #region Variable Declarations
            WpfWindow uIWpfWindow = this.UIMainWindowWindow.UIWpfWindow;
            WinTreeItem uIНовыйтомGTreeItem = this.UIОткрытиеWindow.UIДеревоWindow.UIРабочийстолTreeItem.UIЭтоткомпьютерTreeItem.UIНовыйтомGTreeItem;
            WinEdit uIИмяEdit = this.UIОткрытиеWindow.UIItemWindow.UIFtxtListItem.UIИмяEdit;
            WinButton uIОткрытьButton = this.UIОткрытиеWindow.UIОткрытьWindow.UIОткрытьButton;
            WinTreeItem uIНовыйтомGTreeItem1 = this.UIСохранениеWindow.UIДеревоWindow.UIРабочийстолTreeItem.UIЭтоткомпьютерTreeItem.UIНовыйтомGTreeItem;
            WinComboBox uIИмяфайлаComboBox = this.UIСохранениеWindow.UIПанельподробностейPane.UIИмяфайлаComboBox;
            WinButton uIСохранитьButton = this.UIСохранениеWindow.UIСохранитьWindow.UIСохранитьButton;
            WinControl uIСохранениеDialog = this.UIСохранениеWindow1.UIСохранениеDialog;
            WinButton uIДАButton = this.UIСохранениеWindow1.UIДАWindow.UIДАButton;
            #endregion

            // Щелкните "Wpf" окно
            Mouse.Click(uIWpfWindow, new Point(220, 72));

            // Щелкните "Рабочий стол" -> "Этот компьютер" -> "Новый том (G:)" элемент дерева
            Mouse.Click(uIНовыйтомGTreeItem, new Point(51, 14));

            // Щелкните "Имя" надпись
            Mouse.Click(uIИмяEdit, new Point(69, 14));

            // Щелкните "&Открыть" кнопка
            Mouse.Click(uIОткрытьButton, new Point(56, 12));

            // Щелкните "Wpf" окно
            Mouse.Click(uIWpfWindow, new Point(221, 113));

            // Щелкните "Рабочий стол" -> "Этот компьютер" -> "Новый том (G:)" элемент дерева
            Mouse.Click(uIНовыйтомGTreeItem1, new Point(43, 5));

            // Выберите "g" в "Имя файла:" поле со списком
            uIИмяфайлаComboBox.EditableItem = this.RecordedMethod2Params.UIИмяфайлаComboBoxEditableItem;

            // Щелкните "Со&хранить" кнопка
            Mouse.Click(uIСохранитьButton, new Point(37, 15));

            // Щелкните "Сохранение" Dialog
            Mouse.Click(uIСохранениеDialog, new Point(86, 87));

            // Щелкните "&Да" кнопка
            Mouse.Click(uIДАButton, new Point(39, 11));

            // Щелкните "Wpf" окно
            Mouse.Click(uIWpfWindow, new Point(76, 139));
        }
        
        /// <summary>
        /// Запуск приложения
        /// </summary>
        public void RunApp()
        {

            // Запуск "%USERPROFILE%\source\repos\FGFile\FGFile\bin\Debug\netcoreapp3.1\FGFile.exe"
            ApplicationUnderTest fGFileApplication = ApplicationUnderTest.Launch(this.RunAppParams.ExePath, this.RunAppParams.AlternateExePath);
        }
        
        /// <summary>
        /// Выбор файла f
        /// </summary>
        public void SelectFFile()
        {
            #region Variable Declarations
            WpfButton uIОбзорButton = this.UIMainWindowWindow.UIОбзорButton;
            WinTreeItem uIНовыйтомGTreeItem = this.UIОткрытиеWindow.UIДеревоWindow.UIРабочийстолTreeItem.UIЭтоткомпьютерTreeItem.UIНовыйтомGTreeItem;
            WinEdit uIИмяEdit = this.UIОткрытиеWindow.UIItemWindow.UIFtxtListItem.UIИмяEdit;
            WinButton uIОткрытьButton = this.UIОткрытиеWindow.UIОткрытьWindow.UIОткрытьButton;
            #endregion

            // Щелкните "Обзор" кнопка
            Mouse.Click(uIОбзорButton, new Point(15, 8));

            // Щелкните "Рабочий стол" -> "Этот компьютер" -> "Новый том (G:)" элемент дерева
            Mouse.Click(uIНовыйтомGTreeItem, new Point(58, 12));

            // Щелкните "Имя" надпись
            Mouse.Click(uIИмяEdit, new Point(42, 13));

            // Щелкните "&Открыть" кнопка
            Mouse.Click(uIОткрытьButton, new Point(40, 16));
        }
        
        #region Properties
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public virtual RecordedMethod2Params RecordedMethod2Params
        {
            get
            {
                if ((this.mRecordedMethod2Params == null))
                {
                    this.mRecordedMethod2Params = new RecordedMethod2Params();
                }
                return this.mRecordedMethod2Params;
            }
        }
        
        public virtual RunAppParams RunAppParams
        {
            get
            {
                if ((this.mRunAppParams == null))
                {
                    this.mRunAppParams = new RunAppParams();
                }
                return this.mRunAppParams;
            }
        }
        
        public UIMainWindowWindow UIMainWindowWindow
        {
            get
            {
                if ((this.mUIMainWindowWindow == null))
                {
                    this.mUIMainWindowWindow = new UIMainWindowWindow();
                }
                return this.mUIMainWindowWindow;
            }
        }
        
        public UIОткрытиеWindow UIОткрытиеWindow
        {
            get
            {
                if ((this.mUIОткрытиеWindow == null))
                {
                    this.mUIОткрытиеWindow = new UIОткрытиеWindow();
                }
                return this.mUIОткрытиеWindow;
            }
        }
        
        public UIСохранениеWindow UIСохранениеWindow
        {
            get
            {
                if ((this.mUIСохранениеWindow == null))
                {
                    this.mUIСохранениеWindow = new UIСохранениеWindow();
                }
                return this.mUIСохранениеWindow;
            }
        }
        
        public UIСохранениеWindow1 UIСохранениеWindow1
        {
            get
            {
                if ((this.mUIСохранениеWindow1 == null))
                {
                    this.mUIСохранениеWindow1 = new UIСохранениеWindow1();
                }
                return this.mUIСохранениеWindow1;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private RecordedMethod2Params mRecordedMethod2Params;
        
        private RunAppParams mRunAppParams;
        
        private UIMainWindowWindow mUIMainWindowWindow;
        
        private UIОткрытиеWindow mUIОткрытиеWindow;
        
        private UIСохранениеWindow mUIСохранениеWindow;
        
        private UIСохранениеWindow1 mUIСохранениеWindow1;
        #endregion
    }
    
    /// <summary>
    /// Параметры для передачи в "RecordedMethod1"
    /// </summary>
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.31306.167")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Выберите "g" в "Имя файла:" поле со списком
        /// </summary>
        public string UIИмяфайлаComboBoxEditableItem = "g";
        #endregion
    }
    
    /// <summary>
    /// Параметры для передачи в "RecordedMethod2"
    /// </summary>
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.31306.167")]
    public class RecordedMethod2Params
    {
        
        #region Fields
        /// <summary>
        /// Выберите "g" в "Имя файла:" поле со списком
        /// </summary>
        public string UIИмяфайлаComboBoxEditableItem = "g";
        #endregion
    }
    
    /// <summary>
    /// Параметры для передачи в "RunApp"
    /// </summary>
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.31306.167")]
    public class RunAppParams
    {
        
        #region Fields
        /// <summary>
        /// Запуск "%USERPROFILE%\source\repos\FGFile\FGFile\bin\Debug\netcoreapp3.1\FGFile.exe"
        /// </summary>
        public string ExePath = "C:\\Users\\WhyVilos\\source\\repos\\FGFile\\FGFile\\bin\\Debug\\netcoreapp3.1\\FGFile.exe";
        
        /// <summary>
        /// Запуск "%USERPROFILE%\source\repos\FGFile\FGFile\bin\Debug\netcoreapp3.1\FGFile.exe"
        /// </summary>
        public string AlternateExePath = "%USERPROFILE%\\source\\repos\\FGFile\\FGFile\\bin\\Debug\\netcoreapp3.1\\FGFile.exe";
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.31306.167")]
    public class UIMainWindowWindow : WpfWindow
    {
        
        public UIMainWindowWindow()
        {
            #region Условия поиска
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "MainWindow";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfWindow UIWpfWindow
        {
            get
            {
                if ((this.mUIWpfWindow == null))
                {
                    this.mUIWpfWindow = new WpfWindow(this);
                    #region Условия поиска
                    this.mUIWpfWindow.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
                    this.mUIWpfWindow.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIWpfWindow;
            }
        }
        
        public WpfButton UIОбзорButton
        {
            get
            {
                if ((this.mUIОбзорButton == null))
                {
                    this.mUIОбзорButton = new WpfButton(this);
                    #region Условия поиска
                    this.mUIОбзорButton.SearchProperties[WpfButton.PropertyNames.Name] = "Обзор";
                    this.mUIОбзорButton.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIОбзорButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfWindow mUIWpfWindow;
        
        private WpfButton mUIОбзорButton;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.31306.167")]
    public class UIОткрытиеWindow : WinWindow
    {
        
        public UIОткрытиеWindow()
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Открытие";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Открытие");
            #endregion
        }
        
        #region Properties
        public UIДеревоWindow UIДеревоWindow
        {
            get
            {
                if ((this.mUIДеревоWindow == null))
                {
                    this.mUIДеревоWindow = new UIДеревоWindow(this);
                }
                return this.mUIДеревоWindow;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIОткрытьWindow UIОткрытьWindow
        {
            get
            {
                if ((this.mUIОткрытьWindow == null))
                {
                    this.mUIОткрытьWindow = new UIОткрытьWindow(this);
                }
                return this.mUIОткрытьWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIДеревоWindow mUIДеревоWindow;
        
        private UIItemWindow mUIItemWindow;
        
        private UIОткрытьWindow mUIОткрытьWindow;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.31306.167")]
    public class UIДеревоWindow : WinWindow
    {
        
        public UIДеревоWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "100";
            this.WindowTitles.Add("Открытие");
            #endregion
        }
        
        #region Properties
        public UIРабочийстолTreeItem UIРабочийстолTreeItem
        {
            get
            {
                if ((this.mUIРабочийстолTreeItem == null))
                {
                    this.mUIРабочийстолTreeItem = new UIРабочийстолTreeItem(this);
                }
                return this.mUIРабочийстолTreeItem;
            }
        }
        #endregion
        
        #region Fields
        private UIРабочийстолTreeItem mUIРабочийстолTreeItem;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.31306.167")]
    public class UIРабочийстолTreeItem : WinTreeItem
    {
        
        public UIРабочийстолTreeItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinTreeItem.PropertyNames.Name] = "Рабочий стол";
            this.SearchProperties["Value"] = "0";
            this.WindowTitles.Add("Открытие");
            #endregion
        }
        
        #region Properties
        public UIЭтоткомпьютерTreeItem UIЭтоткомпьютерTreeItem
        {
            get
            {
                if ((this.mUIЭтоткомпьютерTreeItem == null))
                {
                    this.mUIЭтоткомпьютерTreeItem = new UIЭтоткомпьютерTreeItem(this);
                }
                return this.mUIЭтоткомпьютерTreeItem;
            }
        }
        #endregion
        
        #region Fields
        private UIЭтоткомпьютерTreeItem mUIЭтоткомпьютерTreeItem;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.31306.167")]
    public class UIЭтоткомпьютерTreeItem : WinTreeItem
    {
        
        public UIЭтоткомпьютерTreeItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinTreeItem.PropertyNames.Name] = "Этот компьютер";
            this.SearchProperties["Value"] = "1";
            this.SearchConfigurations.Add(SearchConfiguration.ExpandWhileSearching);
            this.SearchConfigurations.Add(SearchConfiguration.NextSibling);
            this.WindowTitles.Add("Открытие");
            #endregion
        }
        
        #region Properties
        public WinTreeItem UIНовыйтомGTreeItem
        {
            get
            {
                if ((this.mUIНовыйтомGTreeItem == null))
                {
                    this.mUIНовыйтомGTreeItem = new WinTreeItem(this);
                    #region Условия поиска
                    this.mUIНовыйтомGTreeItem.SearchProperties[WinTreeItem.PropertyNames.Name] = "Новый том (G:)";
                    this.mUIНовыйтомGTreeItem.SearchProperties["Value"] = "2";
                    this.mUIНовыйтомGTreeItem.SearchConfigurations.Add(SearchConfiguration.ExpandWhileSearching);
                    this.mUIНовыйтомGTreeItem.SearchConfigurations.Add(SearchConfiguration.NextSibling);
                    this.mUIНовыйтомGTreeItem.WindowTitles.Add("Открытие");
                    #endregion
                }
                return this.mUIНовыйтомGTreeItem;
            }
        }
        #endregion
        
        #region Fields
        private WinTreeItem mUIНовыйтомGTreeItem;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.31306.167")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Просмотр элементов";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DirectUIHWND";
            this.WindowTitles.Add("Открытие");
            #endregion
        }
        
        #region Properties
        public UIFtxtListItem UIFtxtListItem
        {
            get
            {
                if ((this.mUIFtxtListItem == null))
                {
                    this.mUIFtxtListItem = new UIFtxtListItem(this);
                }
                return this.mUIFtxtListItem;
            }
        }
        #endregion
        
        #region Fields
        private UIFtxtListItem mUIFtxtListItem;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.31306.167")]
    public class UIFtxtListItem : WinListItem
    {
        
        public UIFtxtListItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinListItem.PropertyNames.Name] = "f.txt";
            this.WindowTitles.Add("Открытие");
            #endregion
        }
        
        #region Properties
        public WinEdit UIИмяEdit
        {
            get
            {
                if ((this.mUIИмяEdit == null))
                {
                    this.mUIИмяEdit = new WinEdit(this);
                    #region Условия поиска
                    this.mUIИмяEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Имя";
                    this.mUIИмяEdit.WindowTitles.Add("Открытие");
                    #endregion
                }
                return this.mUIИмяEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIИмяEdit;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.31306.167")]
    public class UIОткрытьWindow : WinWindow
    {
        
        public UIОткрытьWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1";
            this.WindowTitles.Add("Открытие");
            #endregion
        }
        
        #region Properties
        public WinButton UIОткрытьButton
        {
            get
            {
                if ((this.mUIОткрытьButton == null))
                {
                    this.mUIОткрытьButton = new WinButton(this);
                    #region Условия поиска
                    this.mUIОткрытьButton.SearchProperties[WinButton.PropertyNames.Name] = "Открыть";
                    this.mUIОткрытьButton.WindowTitles.Add("Открытие");
                    #endregion
                }
                return this.mUIОткрытьButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIОткрытьButton;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.31306.167")]
    public class UIСохранениеWindow : WinWindow
    {
        
        public UIСохранениеWindow()
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Сохранение";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Сохранение");
            #endregion
        }
        
        #region Properties
        public UIПанельподробностейPane UIПанельподробностейPane
        {
            get
            {
                if ((this.mUIПанельподробностейPane == null))
                {
                    this.mUIПанельподробностейPane = new UIПанельподробностейPane(this);
                }
                return this.mUIПанельподробностейPane;
            }
        }
        
        public UIСохранитьWindow UIСохранитьWindow
        {
            get
            {
                if ((this.mUIСохранитьWindow == null))
                {
                    this.mUIСохранитьWindow = new UIСохранитьWindow(this);
                }
                return this.mUIСохранитьWindow;
            }
        }
        
        public UIДеревоWindow1 UIДеревоWindow
        {
            get
            {
                if ((this.mUIДеревоWindow == null))
                {
                    this.mUIДеревоWindow = new UIДеревоWindow1(this);
                }
                return this.mUIДеревоWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIПанельподробностейPane mUIПанельподробностейPane;
        
        private UIСохранитьWindow mUIСохранитьWindow;
        
        private UIДеревоWindow1 mUIДеревоWindow;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.31306.167")]
    public class UIПанельподробностейPane : WinPane
    {
        
        public UIПанельподробностейPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinControl.PropertyNames.Name] = "Панель подробностей";
            this.WindowTitles.Add("Сохранение");
            #endregion
        }
        
        #region Properties
        public WinComboBox UIИмяфайлаComboBox
        {
            get
            {
                if ((this.mUIИмяфайлаComboBox == null))
                {
                    this.mUIИмяфайлаComboBox = new WinComboBox(this);
                    #region Условия поиска
                    this.mUIИмяфайлаComboBox.SearchProperties[WinComboBox.PropertyNames.Name] = "Имя файла:";
                    this.mUIИмяфайлаComboBox.WindowTitles.Add("Сохранение");
                    #endregion
                }
                return this.mUIИмяфайлаComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUIИмяфайлаComboBox;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.31306.167")]
    public class UIСохранитьWindow : WinWindow
    {
        
        public UIСохранитьWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1";
            this.WindowTitles.Add("Сохранение");
            #endregion
        }
        
        #region Properties
        public WinButton UIСохранитьButton
        {
            get
            {
                if ((this.mUIСохранитьButton == null))
                {
                    this.mUIСохранитьButton = new WinButton(this);
                    #region Условия поиска
                    this.mUIСохранитьButton.SearchProperties[WinButton.PropertyNames.Name] = "Сохранить";
                    this.mUIСохранитьButton.WindowTitles.Add("Сохранение");
                    #endregion
                }
                return this.mUIСохранитьButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIСохранитьButton;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.31306.167")]
    public class UIДеревоWindow1 : WinWindow
    {
        
        public UIДеревоWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "100";
            this.WindowTitles.Add("Сохранение");
            #endregion
        }
        
        #region Properties
        public UIРабочийстолTreeItem1 UIРабочийстолTreeItem
        {
            get
            {
                if ((this.mUIРабочийстолTreeItem == null))
                {
                    this.mUIРабочийстолTreeItem = new UIРабочийстолTreeItem1(this);
                }
                return this.mUIРабочийстолTreeItem;
            }
        }
        #endregion
        
        #region Fields
        private UIРабочийстолTreeItem1 mUIРабочийстолTreeItem;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.31306.167")]
    public class UIРабочийстолTreeItem1 : WinTreeItem
    {
        
        public UIРабочийстолTreeItem1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinTreeItem.PropertyNames.Name] = "Рабочий стол";
            this.SearchProperties["Value"] = "0";
            this.WindowTitles.Add("Сохранение");
            #endregion
        }
        
        #region Properties
        public UIЭтоткомпьютерTreeItem1 UIЭтоткомпьютерTreeItem
        {
            get
            {
                if ((this.mUIЭтоткомпьютерTreeItem == null))
                {
                    this.mUIЭтоткомпьютерTreeItem = new UIЭтоткомпьютерTreeItem1(this);
                }
                return this.mUIЭтоткомпьютерTreeItem;
            }
        }
        #endregion
        
        #region Fields
        private UIЭтоткомпьютерTreeItem1 mUIЭтоткомпьютерTreeItem;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.31306.167")]
    public class UIЭтоткомпьютерTreeItem1 : WinTreeItem
    {
        
        public UIЭтоткомпьютерTreeItem1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinTreeItem.PropertyNames.Name] = "Этот компьютер";
            this.SearchProperties["Value"] = "1";
            this.SearchConfigurations.Add(SearchConfiguration.ExpandWhileSearching);
            this.SearchConfigurations.Add(SearchConfiguration.NextSibling);
            this.WindowTitles.Add("Сохранение");
            #endregion
        }
        
        #region Properties
        public WinTreeItem UIНовыйтомGTreeItem
        {
            get
            {
                if ((this.mUIНовыйтомGTreeItem == null))
                {
                    this.mUIНовыйтомGTreeItem = new WinTreeItem(this);
                    #region Условия поиска
                    this.mUIНовыйтомGTreeItem.SearchProperties[WinTreeItem.PropertyNames.Name] = "Новый том (G:)";
                    this.mUIНовыйтомGTreeItem.SearchProperties["Value"] = "2";
                    this.mUIНовыйтомGTreeItem.SearchConfigurations.Add(SearchConfiguration.ExpandWhileSearching);
                    this.mUIНовыйтомGTreeItem.SearchConfigurations.Add(SearchConfiguration.NextSibling);
                    this.mUIНовыйтомGTreeItem.WindowTitles.Add("Сохранение");
                    #endregion
                }
                return this.mUIНовыйтомGTreeItem;
            }
        }
        #endregion
        
        #region Fields
        private WinTreeItem mUIНовыйтомGTreeItem;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.31306.167")]
    public class UIСохранениеWindow1 : WinWindow
    {
        
        public UIСохранениеWindow1()
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Сохранение";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.FilterProperties[WinWindow.PropertyNames.OrderOfInvocation] = "2";
            this.WindowTitles.Add("Сохранение");
            #endregion
        }
        
        #region Properties
        public UIДАWindow UIДАWindow
        {
            get
            {
                if ((this.mUIДАWindow == null))
                {
                    this.mUIДАWindow = new UIДАWindow(this);
                }
                return this.mUIДАWindow;
            }
        }
        
        public WinControl UIСохранениеDialog
        {
            get
            {
                if ((this.mUIСохранениеDialog == null))
                {
                    this.mUIСохранениеDialog = new WinControl(this);
                    #region Условия поиска
                    this.mUIСохранениеDialog.SearchProperties[UITestControl.PropertyNames.Name] = "Сохранение";
                    this.mUIСохранениеDialog.SearchProperties[UITestControl.PropertyNames.ControlType] = "Dialog";
                    this.mUIСохранениеDialog.WindowTitles.Add("Сохранение");
                    #endregion
                }
                return this.mUIСохранениеDialog;
            }
        }
        #endregion
        
        #region Fields
        private UIДАWindow mUIДАWindow;
        
        private WinControl mUIСохранениеDialog;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.31306.167")]
    public class UIДАWindow : WinWindow
    {
        
        public UIДАWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "6";
            this.WindowTitles.Add("Сохранение");
            #endregion
        }
        
        #region Properties
        public WinButton UIДАButton
        {
            get
            {
                if ((this.mUIДАButton == null))
                {
                    this.mUIДАButton = new WinButton(this);
                    #region Условия поиска
                    this.mUIДАButton.SearchProperties[WinButton.PropertyNames.Name] = "Да";
                    this.mUIДАButton.WindowTitles.Add("Сохранение");
                    #endregion
                }
                return this.mUIДАButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIДАButton;
        #endregion
    }
}
